dtc: bump to 1.6.1
The following error occurred while building:

In file included from fdtdump.c:14:
In function 'fdt_set_magic',
    inlined from 'main' at fdtdump.c:220:3:
libfdt/libfdt.h:251:28: error: array subscript 'struct fdt_header[0]' is partly outside array bounds of 'unsigned char[4]' [-Werror=array-bounds]
  251 |                 fdth->name = cpu_to_fdt32(val); \
      |                 ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
libfdt/libfdt.h:253:1: note: in expansion of macro 'fdt_set_hdr_'
  253 | fdt_set_hdr_(magic);
      | ^~~~~~~~~~~~
fdtdump.c: In function 'main':
fdtdump.c:216:31: note: object 'smagic' of size 4
  216 |                 unsigned char smagic[FDT_MAGIC_SIZE];
      |                               ^~~~~~

According to some reports, this issue has been fixed in dtc 1.6.1 .

Signed-off-by: Ethan Zuo <yuxuan.zuo@outlook.com>